### ISSUE TITLE
Sort by amount of drops?

### ISSUE THREAD

**Issue by Kaytiecakes** [AlexanderSharykin/CardIdleRemastered#10]
Hi back again! 

Is there a way to sort the queue list by amount of drops remaining?
At the moment I have 442 games left to idle and I'm going bonkers scrolling for games with the highest drop and pressing the "^" to bring them to the top.

Is there a fast way to sort it by drops remaining that I'm missing?

Thanks for your help!
KT

**Comment by AlexanderSharykin** [comment]
Hi!
Only Badges table is sortable. Queue is NOT sortable by design (sorting the queue defeats its purpose). 

To have a queue ordered by card drops you should add them in that order. To do it *quickly* use the following method:

1. stop idling on Queue tab if it is running
2. switch to Badges tab. disable filters if there any.
click Remove All under the badges table to CLEAR CURRENT QUEUE
3. on Badges tab: click on "Cards" table header to sort by card drops remaining Ascending or Descending
4. click Add All under the badges table to add ordered badges to queue

**Comment by Kaytiecakes** [comment]
Okay thanks :)
