### ISSUE TITLE
No Refresh button?

### ISSUE THREAD

**Issue by Triangle333** [AlexanderSharykin/CardIdleRemastered#12]
I see the following problems:
1. App doesn't show in taskbar - inconvenient
2. Card drops isn't detected by app momentarily - card counts aren't updated. Maybe this happens every 5 mins or so, but sometimes user doesn`t want to wait. Manual "Refresh" button can fix this problem.
3. Why "Periodic Switch Repeat Count" is 1 by default? Why do we need this parameter at all? "Periodic Idle" mode must grind on until all cards received, then stop; not some fixed repeat number.
4. Where is the "Queue Everything" button? I don`t want to queue 50 games 1 by 1...

**Comment by AlexanderSharykin** [comment]
1. inconvenient? is it? some people say exactly the opposite: https://github.com/AlexanderSharykin/CardIdleRemastered/issues/9.
Enable/disable taskbar icon using "Show in taskbar" option in Settings

2. There is undocument feature: open Badges tab and press F5 to force sync. I will add button with the same function in the next release.

3. 1 is minimal possible valid value, therefore is default.
"Periodic Idle" is a sort of a "hack" which works for some users. For other it may grind ad infinitum and do nothing.
If "Periodic Idle" works for you and gives a card for each game on each run, then set a large "Periodic Switch Repeat Count" and lauch idle. It will grind on until all cards received

4. has already been asked before: https://github.com/AlexanderSharykin/CardIdleRemastered/issues/6
Badges tab, buttons [^] and [v] under the list of badges

**Comment by Triangle333** [comment]
1. Found it.
2. Please do
3. Tried Periodic and it sucks. What really works for me is:
a) Idle 10 games at once for 30 mins
b) Stop all and wait 30 seconds, 4-5 cards will drop
c) Start all 10 again. It will be reasonable at this point to check for finished games first and remove them from the list before launching
d) Wait for 10-15 mins and go to step b)
Can you add this idling mode?
4. Yeah, found it shortly after creating issue. Maybe add more meaningful tooltip?

**Comment by AlexanderSharykin** [comment]
2. refresh button is available in release 2.4.3
3. sounds like you misunderstood what Periodic mode does
it is not "Periodic Idle", it is "Periodic Switch". It is sort of a hack, and I will repeat its description:

"Due to changes in Steam card drop system it became possible to get 1 card drop with a simple method: 1. launch a game from library 2. wait some time 3. quit the game. "Periodic Switch" mode automates the process. Card Idle starts the 1st game from the queue, waits for a short interval, stops the game, waits a bit for Steam to react (and possibly drop a card), starts the 2nd game from the queue, waits, stops it, etc, repeat for all games in the queue."

What really works for me is:
a) Idle a group of games at once for 30 mins
b) Stop all and wait 30 seconds, a few cards will drop
c) change mode to "Periodic switch" and run it once. games which didn't give a card at step b) will drop 1 card
d) refresh badges list
e) repeat a)-d) for remaining games

I'm reluctant to automate a)-e) process because switching method works for 50% of steam users, and can stop working after any steam update

**Comment by Triangle333** [comment]
Thanx!
