### ISSUE TITLE
Not functioning correctly?

### ISSUE THREAD

**Issue by morrison98** [AlexanderSharykin/CardIdleRemastered#16]
I just downloaded the card idle, but, after loggin in, does not show any game that i have nor any idle
![image](https://user-images.githubusercontent.com/39442636/40271730-5e856d40-5b6f-11e8-95bc-17028813ea5a.png)

**Comment by AlexanderSharykin** [comment]
Idle Master and Card Idle have never shown list of games which user owns. Both programs show a list of games which have cards and have remaining card drops.
Additionally Card Idle shows all badges which can be collected and crafted on showcases tab.

Do you have any remaining card drops? or any cards at all?

**Comment by AlexanderSharykin** [comment]
@NoDaLie,
if Card Idle loaded Showcases then it means that badges pages were read properly

I have several possible explanations for empty Badges tab:

1. some "Filters" are applied. Click Filters and check "Any" for each option to disable them

2. an error happened. if it so, then file "error.log" in Card Idle folder should contain some long and scary exception message

3. there is nothing to show you don't really have remaining card drops. judging by the time you spent in your games it is very possible

**Comment by NoDaLie** [comment]
@AlexanderSharykin 
1. I have all filters on Any

2. Doesn't look like an error:
09.06.2018 21:53:17   Microsoft Windows NT 6.2.9200.0 64bit
09.06.2018 21:53:17   Settings storage initialized
09.06.2018 21:53:18   Session test
09.06.2018 21:53:19   Welcome back
09.06.2018 21:53:21   Showcase storage initialized

3.  Do you mean that I spent too less time in the games or too much and is there a limit of card drops, so that I have to buy the remaining cards? So the term "remaining card drops" is a bit unclear to me.

And I actually still don't have any badges, I don't have even one game with all cards. Does that have anything to do with the issue?

**Comment by AlexanderSharykin** [comment]
3. "**remaining** card drops" means cards which you can get from Steam for free while playing games.
it is explained in https://steamcommunity.com/tradingcards/faq

normal way to get card drops: download a game, launch it, play it, get card drops while playing. (without "remaining card drops" you just enjoy the game. I hope I'm not the only one who can do that nowdays)

Steam gives only half of a set! they want to make $, so users who want to get a badge have to buy the **missing** cards (or exchange them which does not require funds, but takes more time)

"idling" way: download a game, launch it, don't play it, just wait and cards will drop after some time. 
without "remaining card drops" idling is useless.

"idling" programs take a step further: instead of downloading each game, Idle Master and Card Idle use special app, which pretends to be a "game", but does not waste HDD space, RAM and CPU resources. IM and CardIdle launch launch the app, then just wait when cards will drop after some time

Card Idle has limited usage without "remaining card drops": with Showcases features it shows badges available for crafting, so users can plan what they will craft, exchange, buy or sell. If you decide to collect some set and need to exchange card, middle-click on game image on Showcases tab will take you to a decent card trading bot

**Comment by NoDaLie** [comment]
@AlexanderSharykin 
So for some games I indeed have no card drops left, but for instance for CIVILIZATION VI I have only 2 out of 8 cards, so if I understood you correctly, at least this game should be displayed in the badges tab.
Could I use time idling for getting the other 2 cards, or what is the sense of time idling?

**Comment by AlexanderSharykin** [comment]
It is not about how many cards users have (cards can be bought, sold, exhchanged, converted to gems), it is about how many cards Steam will give for free (limited amount)

idling is useless if there is no games with message like the following:
![hl2](https://user-images.githubusercontent.com/6756469/41242611-b02c779c-6da8-11e8-8552-773ec7b6bdb7.png)

**Comment by AlexanderSharykin** [comment]
system requirements are not met
