### ISSUE TITLE
Why does CIR stop on its own?

### ISSUE THREAD

**Issue by vertigoelectric** [AlexanderSharykin/CardIdleRemastered#23]
I've been using CIR a lot and I've noticed that sometimes I will find that it has stopped idling games on its own even when there are still several games queued to idle.  Sometimes it happens after several hours, but sometimes after only a short while.  

Is this an intentional feature, and if so, what is the reason/cause?

If it's not intentional, what are some reasons it might be happening so I can troubleshoot the problem?

Thanks

EDIT:  Oh yeah, and of course thanks a ton for this awesome app! 👍

**Comment by vertigoelectric** [comment]
> When CIR supposedly stopped, does it shows "Not in game" status and "Start" button is active, or does it show active game count and "Stop" button is active?

"Not in game" status and "Start" button is active

> Do you add/remove games in Queue or change selected idling mode after starting? (TIP: Don't change Idling mode after starting. The selection when idling was disabled originally, but the block was lost in refactoring, it is a minor bug)

No, I am not changing anything after clicking "Start"

> Which mode CIR was in, when it stopped working? Did you use different modes before that? (in the same run)

Periodic Switch

> What is your setting of Max Idle Process Count and how many games were in the Queue?

Max Idle Process Count is set to the maximum of 30, and there are currently 112 items in the Queue.

**Comment by AlexanderSharykin** [comment]
Periodic Switch is a special mode.

One By One, Trial First/Last, All are idling modes, meaning that proceeding games using them takes long time and increases in-game time significantly (ususally +30 min for each game to drop 1 card)

Periodic Switch mode works differently.

"Due to changes in Steam card drop system it became possible to get 1 card drop with a simple method: 1. launch a game from library 2. wait some time 3. quit the game. "Periodic Switch" mode automates the process. Card Idle starts the 1st game from the queue, waits for a short interval, stops the game, waits a bit for Steam to react (and possibly drop a card), starts the 2nd game from the queue, waits, stops it, etc, repeat for all games in the queue."
(please read a discussion about Periodic Switch in this topic: https://github.com/AlexanderSharykin/CardIdleRemastered/issues/12)

In that mode CIR launches each game for 10 seconds and stops when when reach the end of the Queue

**Comment by vertigoelectric** [comment]
OHHHH, I didn't realize Periodic Switch only went through each game once and I didn't realize there was an option to increase this number (Periodic Switch Repeat Count).

Okay that explains why it's stopping then.

Thanks!
