### ISSUE TITLE
Full Reset

### ISSUE THREAD

**Issue by Melidebby** [AlexanderSharykin/CardIdleRemastered#31]
Is it possible to do a full reset?

IE clear all Time Idle and Showcases

I tried deleting the .zip file and the folder I had it extracted in but I'm still seeing all of it.

**Comment by AlexanderSharykin** [comment]
Hi
It is a bit unclear to me what kind of reset you need, because full reset, clear Time Idle and clear Showcases can be done differently.

1. full  reset
Card Idle stores user's preferences in a Settings.txt file, which can be found by the following path:

C:\Users\%Windows_username%\AppData\Local\CardIdleRemastered

quit Card Idle, delete Settings.txt, and the next launch will be with default settings

2. clear Time Idle

on Time Idle page there is [X] button for each selected game. Click it to remove games one by one

alternatively: remove `<Games>some numbers</Games>` node from Settings.txt file

3. clear Showcases

I made Showcases feature to provide help with selection of badges for crafting. All Showcases are loading by default because I made complete (more or less) file of existing badges.

to hide them: open Showcases page and set filter "Bookmarked=Yes". 

to remove Showcases: 
open Settings page and uncheck "Allow Showcases sync" checkbox. This will prevent loading showcases for badges you own.

close CIR, and remove "ShowcasesDb.txt" file from CIR folder. This will prevent loading showcases for badges, you don't own.

restart CIR.

I'm curious though: why do you try to get rid of them? They are intended to be helpful

**Comment by Melidebby** [comment]
thanks I simply deleted Settings.txt and PricesDb.txt and I likely also deleted ShowcasesDb.txt then I deleted the entire CardIdleRemastered off my PC then re-extracted it.

I never used the Showcases feature cause I tend to look through the badges for what I want to grab like Terraria so Showcases didn't seem useful for me cause I have to go through 100's of badges to find the one i'm looking for xD

I might use it in the future but who knows.

and I knew about clicking the X in Time Idle but I wanted to know If you could remove it VIA the file.

I simply like learning about stuff.

Sorry.. I'm weird like that...

**Comment by AlexanderSharykin** [comment]
> have to go through 100's of badges to find the one i'm looking for

not at all. under the table on the right side there is a input field for quick search. type game title there (e.g. "terra") and you will see all matches including "Terraria"

**Comment by Melidebby** [comment]
I did not think of that.... *face palm* xD
